{
 "title": "HTTP Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Status by method [Rate 2m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_count_total{endpoint=\"/cache/<key>\"}[2m])) by (method,http_status)",
     "legendFormat": "{{method}}-{{http_status}}"
    }
   ]
  },
  {
   "title": "Requests by HTTP Method [Rate 2m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_count_total{endpoint=\"/cache/<key>\"}[2m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Cache PUT response latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_latency_seconds_bucket{endpoint=\"/cache/<key>\",method=\"PUT\"}[2m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket{endpoint=\"/cache/<key>\",method=\"PUT\"}[2m])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_latency_seconds_bucket{endpoint=\"/cache/<key>\",method=\"PUT\"}[2m])) by (le))",
     "legendFormat": "50"
    }
   ]
  },
  {
   "title": "Cache GET response latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_latency_seconds_bucket{endpoint=\"/cache/<key>\",method=\"GET\"}[2m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket{endpoint=\"/cache/<key>\",method=\"GET\"}[2m])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_latency_seconds_bucket{endpoint=\"/cache/<key>\",method=\"GET\"}[2m])) by (le))",
     "legendFormat": "50"
    }
   ]
  }
 ]
}